/*************************************************************************************
 ***
 ***  Simulation frame header file: MemMap.h
 ***
 ***  Dummy header file needed for building TL SIL/PIL simulation application
 ***  from TL production code.
 ***
 ***  Generated by dSPACE TargetLink Version 4.3p6 from 26-Feb-2020
 ***  Generation date: 04-Jul-2024 07:50:57
\************************************************************************************/

#ifndef MEMMAP_H
#define MEMMAP_H

#endif
