/**************************************************************************************************\
 *** 
 *** System              : TargetLink Simulation RTE
 *** ECU                 : TL_ECU
 *** Configuration       : NONE
 *** Codefile            : Rte.h
 ***
 *** Generated by the SystemDesk RTE code generator
 *** Generation date: 2024-07-04 07:50:57
 ***
 *** SystemDesk version  : 4.3.0.314576
 *** Copyright (c) 2016 dSPACE GmbH
\**************************************************************************************************/

#ifndef RTE_H
#define RTE_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "RteIv.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/


/******************************************************************************\
   RTE_PREDEFINED_ERRORS: Predefined error codes. | Width: 8
\******************************************************************************/
#define RTE_E_OK (Std_ReturnType) 0 
#define RTE_E_INVALID (Std_ReturnType) 1 
#define RTE_E_LOST_DATA (Std_ReturnType) 64 
#define RTE_E_MAX_AGE_EXCEEDED (Std_ReturnType) 64 
#define RTE_E_COM_STOPPED (Std_ReturnType) 128 
#define RTE_E_TIMEOUT (Std_ReturnType) 129 
#define RTE_E_LIMIT (Std_ReturnType) 130 
#define RTE_E_NO_DATA (Std_ReturnType) 131 
#define RTE_E_TRANSMIT_ACK (Std_ReturnType) 132 
#define RTE_E_NEVER_RECEIVED (Std_ReturnType) 133 
#define RTE_E_WAITING (Std_ReturnType) 191 

/******************************************************************************\
   DEFINE_16BIT: defined preprocessor macros | Width: 16
\******************************************************************************/
#define Rte_InitValue_add_SoftwareComponent_input1_new_DataElement (sint16) 0 
#define Rte_InitValue_add_SoftwareComponent_input2_new_DataElement (sint16) 0 
#define Rte_InitValue_add_SoftwareComponent_output_new_DataElement (sint16) 0 
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/


/* Definition of a component data structure. */
typedef struct {
   Rte_DE_sint16 * add_runnable_input1_new_DataElement;
   Rte_DE_sint16 * add_runnable_input2_new_DataElement;
   Rte_DE_sint16 * add_runnable_output_new_DataElement;
} Rte_CDS_add_SoftwareComponent;
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */ 


/******************************************************************************\
   VAR_NOINIT_16BIT: global or static variables (RAM) | Width: 16
\******************************************************************************/
extern sint16 Rte_add_SoftwareComponent_input1_new_DataElement;
extern sint16 Rte_add_SoftwareComponent_input2_new_DataElement;
extern sint16 Rte_add_SoftwareComponent_output_new_DataElement;

/******************************************************************************\
   CONST_UNSPECIFIED: global or static constants (ROM) | Width: N.A.
\******************************************************************************/
extern const Rte_CDS_add_SoftwareComponent Rte_Instance_add_SoftwareComponent;
extern const Rte_CDS_add_SoftwareComponent * Rte_Inst_add_SoftwareComponent;
#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */ 

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/


/* API functions */
#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */ 

extern void Task_add_runnable(void);
#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */ 


#endif/*RTE_H */
/*----------------------------------------------------------------------------*\
 END OF FILE
\*----------------------------------------------------------------------------*/
