/**************************************************************************************************\
 *** 
 *** System              : TargetLink Simulation RTE
 *** ECU                 : TL_ECU
 *** Configuration       : NONE
 *** Codefile            : Rte_add_SoftwareComponent.h
 ***
 *** Generated by the SystemDesk RTE code generator
 *** Generation date: 2024-07-04 07:50:57
 ***
 *** SystemDesk version  : 4.3.0.314576
 *** Copyright (c) 2016 dSPACE GmbH
\**************************************************************************************************/

#ifndef RTE_ADD_SOFTWARECOMPONENT_H
#define RTE_ADD_SOFTWARECOMPONENT_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

#ifndef RTE_C
#ifndef RTE_ADD_SOFTWARECOMPONENT_C

/* Init value(s). */
#define Rte_InitValue_input1_new_DataElement 0 
#define Rte_InitValue_input2_new_DataElement 0 
#define Rte_InitValue_output_new_DataElement 0 
#endif 
#endif 
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/

#ifndef RTE_C
#ifndef RTE_ADD_SOFTWARECOMPONENT_C
typedef const Rte_CDS_add_SoftwareComponent * const Rte_Instance;
#endif 
#endif 
/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/

#ifndef RTE_C
#ifndef RTE_ADD_SOFTWARECOMPONENT_C

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_add_runnable_input1_new_DataElement
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      sint16
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_add_runnable_input1_new_DataElement() \
(\
   (Rte_Inst_add_SoftwareComponent->add_runnable_input1_new_DataElement->value)\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IRead_add_runnable_input2_new_DataElement
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit read on a sender-receiver communication data item with data semantics
 .
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      sint16
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IRead_add_runnable_input2_new_DataElement() \
(\
   (Rte_Inst_add_SoftwareComponent->add_runnable_input2_new_DataElement->value)\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWrite_add_runnable_output_new_DataElement
 ***
 ***  DESCRIPTION:
 ***      Performs an "implicit" write on a sender-receiver communication data with "data" semantics
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***      sint16             new_DataElement     
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWrite_add_runnable_output_new_DataElement(new_DataElement) \
(\
   (Rte_Inst_add_SoftwareComponent->add_runnable_output_new_DataElement->value) = (new_DataElement)\
)

/*************************************************************************************************\
 ***  PARAMETERIZED MACRO:
 ***      Rte_IWriteRef_add_runnable_output_new_DataElement
 ***
 ***  DESCRIPTION:
 ***      Performs an implicit write on a sender-receiver communication data item with data semantic
 s.
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      sint16 *
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
#define Rte_IWriteRef_add_runnable_output_new_DataElement() \
(\
   ((sint16 *) (&(Rte_Inst_add_SoftwareComponent->add_runnable_output_new_DataElement->value)))\
)

#endif 
#endif 
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/


/* runnables */
#ifdef __cplusplus
 extern "C" {
#endif /* __cplusplus */ 

extern void add_runnable(void);
#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */ 


#endif/*RTE_ADD_SOFTWARECOMPONENT_H */
/*----------------------------------------------------------------------------*\
 END OF FILE
\*----------------------------------------------------------------------------*/
