/*************************************************************************************
 ***
 ***  Simulation frame header file: tl_types.h
 ***
 ***  Definitions of the TargetLink data types.
 ***
 ***  Generated by dSPACE TargetLink, version 4.3p6 from 26-Feb-2020
 ***  Generation date: 04-Jul-2024 07:50:58
\************************************************************************************/

#ifndef TL_TYPES_H
#define TL_TYPES_H

#include "Rte_Type.h" 

#endif
