/**************************************************************************************************\
 *** 
 *** System              : TargetLink Simulation RTE
 *** ECU                 : TL_ECU
 *** Configuration       : NONE
 *** Codefile            : Rte.c
 ***
 *** Generated by the SystemDesk RTE code generator
 *** Generation date: 2024-06-26 10:27:02
 ***
 *** SystemDesk version  : 4.3.0.314576
 *** Copyright (c) 2016 dSPACE GmbH
\**************************************************************************************************/

#ifndef RTE_C
#define RTE_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte.h"
#include "Rte_driver_SoftwareComponent.h"
#include "Rte_Main.h"
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/


/******************************************************************************\
   VAR_NOINIT_16BIT: global or static variables (RAM) | Width: 16
\******************************************************************************/
sint16 Rte_driver_SoftwareComponent_Out1_new_DataElement;
sint16 Rte_driver_SoftwareComponent_Out2_new_DataElement;

/******************************************************************************\
   CONST_UNSPECIFIED: global or static constants (ROM) | Width: N.A.
\******************************************************************************/

/* Definition of an instance for component driver_SoftwareComponent of type driver_SoftwareComponent
   . */
const Rte_CDS_driver_SoftwareComponent Rte_Instance_driver_SoftwareComponent = {
   ((Rte_DE_sint16 *) &Rte_driver_SoftwareComponent_Out1_new_DataElement), 
   ((Rte_DE_sint16 *) &Rte_driver_SoftwareComponent_Out2_new_DataElement)
};

/* Definition of an instance handle for component driver_SoftwareComponent of type driver_SoftwareCo
   mponent. */
const Rte_CDS_driver_SoftwareComponent * Rte_Inst_driver_SoftwareComponent =
    &Rte_Instance_driver_SoftwareComponent;
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Task_driver_runnable
 ***
 ***  DESCRIPTION:
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      void
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
void Task_driver_runnable(void)
{

   /* Starts a runnable. */
   driver_runnable();
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_Start
 ***
 ***  DESCRIPTION:
 ***      Rte_Start is for allocating and initializing system resources and communication resources 
 ***      used by the RTE.
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      Std_ReturnType
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
Std_ReturnType Rte_Start(void)
{
   Rte_driver_SoftwareComponent_Out1_new_DataElement =
    Rte_InitValue_driver_SoftwareComponent_Out1_new_DataElement;
   Rte_driver_SoftwareComponent_Out2_new_DataElement =
    Rte_InitValue_driver_SoftwareComponent_Out2_new_DataElement;

   /* API call return. */
   return RTE_E_OK;
}

/*************************************************************************************************\
 ***  FUNCTION:
 ***      Rte_Stop
 ***
 ***  DESCRIPTION:
 ***      Rte_Stop is used to finalize the RTE itself. This service releases all system and communic
 ***      ation resources allocated by the RTE.
 ***
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
 ***
 ***  RETURNS:
 ***      Std_ReturnType
 ***
 ***  SETTINGS:
 ***
\*************************************************************************************************/
Std_ReturnType Rte_Stop(void)
{

   /* API call return. */
   return RTE_E_OK;
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/


#endif/*RTE_C */
/*----------------------------------------------------------------------------*\
 END OF FILE
\*----------------------------------------------------------------------------*/
