#=======================================================================
# MAKE-file segment:  driver.mk
#
# Generated by dSPACE TargetLink Version 4.3p6 from 26-Feb-2020
# Generation date: 2024-07-04 08:56:50 
#=======================================================================


#-----------------------------------------------------------------------
# MakeFile.mk options
#-----------------------------------------------------------------------

LOGDATA=ON
MCU=x86_64
COMPILER=GCC
BOARD=HostPC64
D_SIM=TLBuild
MakefileSupportsQuotedPath=1
COMP_ROOT=C:\Tools\MinGW_CC++_Compiler_5.3  # directory where the compiler is installed
PROD_CODE_BUILDER=C:\Program Files\dSPACE TargetLink 4.3\Matlab\Tl\ApplicationBuilder  # directory prod. code builder
UTILITY_ROOT=C:\Program Files\dSPACE TargetLink 4.3\Matlab\Tl\ApplicationBuilder\bin  # directory where TL utilities are installed
DSFXP_SRC_ROOT=C:\ProgramData\dSPACE\0163BCB4-9093-43BC-B3EF-CC570F9DBD41\Archives\FxpLibSrc  # directory where DSFxp is installed
SIMULATION_PACKAGE=C:\Program Files\dSPACE TargetLink 4.3\Matlab\Tl\ApplicationBuilder\BoardPackages\HostPC64\GCC  # directory where plattform sources are installed
GENERIC_SRC_ROOT=C:\Program Files\dSPACE TargetLink 4.3\Matlab\Tl\SimFiles\generic  # directory where generic sources are installed
COMP_OPT=
USE_OSEK_EMULATOR=OFF
ShowAllWarnings=0
ACCESS_POINTS_DISABLE=ON
COMPILE_ONLY=OFF

TL_MAX_SIM_OBJECTS=2
TL_MAX_SIM_LISTS=7
TL_MAX_SIM_VARS=2


#-----------------------------------------------------------------------
# System/CodeGenerationUnit "driver/driver/Subsystem/driver":
#-----------------------------------------------------------------------

# application source file list - full names
DRIVER_APPL_SRC_FILES := \
   ".\TLBuild\driver\HostPC64_GCC\driver.c" \

# application library file list
DRIVER_APPL_LIB_FILES := \


# application object file list
DRIVER_APPL_OBJ_FILES := \

# production code frame - full names
DRIVER_CALLER_FCN_SRC_FILE := \
   ".\TLBuild\driver\HostPC64_GCC\driver_fri.c" \
   ".\TLBuild\driver\HostPC64_GCC\driver_pcf.c" \

# file dependencies
driver.obj :  "driver.c" "driver.h" "tl_basetypes.h"
driver_fri.obj :  "driver_fri.c" "driver_fri.h" "tl_basetypes.h" "tl_types.h" "driver_frm.h"
driver_pcf.obj :  "driver_pcf.c" "driver_fri.h" "ts_frame.h"


#-----------------------------------------------------------------------
# List of RTE frame files generated by the RTE code generator
#-----------------------------------------------------------------------
RTE_FRAME_FILES := \


#-----------------------------------------------------------------------
# List of source files
#-----------------------------------------------------------------------
APPL_SRC_FILES := \
   $(DRIVER_APPL_SRC_FILES) \

CALLER_SRC_FILES := \
   $(DRIVER_CALLER_FCN_SRC_FILE) \
   $(RTE_FRAME_FILES) \


#-----------------------------------------------------------------------
# List of object files
#-----------------------------------------------------------------------
APPL_OBJ_FILES := \
   $(DRIVER_APPL_OBJ_FILES) \


#-----------------------------------------------------------------------
# List of library files
#-----------------------------------------------------------------------
MODEL_LIB_PATH := \
   C:\Program Files\dSPACE TargetLink 4.3\Matlab\Tl\ApplicationBuilder\BoardPackages\HostPC64\GCC

MODEL_LIB_FILES := \
   $(DRIVER_APPL_LIB_FILES) \


#-----------------------------------------------------------------------
# User-defined include paths
#-----------------------------------------------------------------------
USR_INC_PATHS := \
   ".\TLBuild\driver\HostPC64_GCC" \

# [EOF]

